import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { Menu, X, Utensils } from "lucide-react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { BrandProvider } from '@/components/brand-demo/BrandProvider';
import { OnboardingModal, BrandResetButton } from '@/components/brand-demo/OnboardingModal';

function NotFoundComponent() { return (<div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="font-display text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition hover:opacity-90">Go home</Link></div></div></div>); }
function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) { console.error(error); const router = useRouter(); useEffect(() => { reportLovableError(error, { boundary: "tanstack_root_error_component" }); }, [error]); return (<div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong. Try refreshing or head back home.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={() => { router.invalidate(); reset(); }} className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90">Try again</button><a href="/" className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent">Go home</a></div></div></div>); }
export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({ head: () => ({ meta: [{ charSet: "utf-8" }, { name: "viewport", content: "width=device-width, initial-scale=1" }], links: [{ rel: "stylesheet", href: appCss }, { rel: "preconnect", href: "https://fonts.googleapis.com" }, { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" }, { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@600;700;800&display=swap" }] }), shellComponent: RootShell, component: RootComponent, notFoundComponent: NotFoundComponent, errorComponent: ErrorComponent });
function RootShell({ children }: { children: ReactNode }) { return <html lang="en"><head><HeadContent /></head><body>{children}<Scripts /></body></html>; }
const nav = [{ to: "/", label: "Home" }, { to: "/menus", label: "Menus" }, { to: "/events", label: "Events" }, { to: "/about", label: "About" }, { to: "/contact", label: "Contact" }] as const;
function SiteHeader() { const [open, setOpen] = useState(false); return (<header className="sticky top-0 z-40 border-b border-border bg-background/85 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><Link to="/" className="flex items-center gap-2"><Utensils className="h-6 w-6 text-primary" /><span className="font-display text-2xl font-bold tracking-tight"><span data-brand-text="business-name">Om Shree Krishna Caterer</span></span></Link><nav className="hidden gap-8 md:flex">{nav.map((n) => <Link key={n.to} to={n.to} className="text-sm font-medium text-foreground/80 transition hover:text-primary" activeProps={{ className: "text-primary" }} activeOptions={{ exact: n.to === "/" }}>{n.label}</Link>)}</nav><Link to="/contact" className="hidden rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:opacity-90 md:inline-block">Book us</Link><button className="md:hidden" onClick={() => setOpen((v) => !v)} aria-label="Toggle menu">{open ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}</button></div>{open && <div className="border-t border-border bg-background md:hidden"><nav className="mx-auto flex max-w-6xl flex-col px-6 py-4">{nav.map((n) => <Link key={n.to} to={n.to} onClick={() => setOpen(false)} className="py-2 text-sm font-medium" activeProps={{ className: "text-primary" }} activeOptions={{ exact: n.to === "/" }}>{n.label}</Link>)}</nav></div>}</header>); }
function SiteFooter() { return (<footer className="border-t border-border bg-secondary/40"><div className="mx-auto grid max-w-6xl gap-8 px-6 py-12 md:grid-cols-4"><div><div className="flex items-center gap-2"><Utensils className="h-5 w-5 text-primary" /><span className="font-display text-xl font-bold" data-brand-text="business-name">Om Shree Krishna Caterer</span></div><p className="mt-3 text-sm text-muted-foreground">Professional catering and catering equipment rental services for weddings, parties, corporate events and celebrations.</p></div><div><h4 className="mb-3 text-sm font-semibold">Explore</h4><ul className="space-y-2 text-sm text-muted-foreground">{nav.map((n) => <li key={n.to}><Link to={n.to} className="hover:text-primary">{n.label}</Link></li>)}</ul></div><div><h4 className="mb-3 text-sm font-semibold">Contact</h4><ul className="space-y-2 text-sm text-muted-foreground"><li data-brand-text="phone">+91 94332 51917</li><li data-brand-text="address">32, Jelia Para Ln, Babudanga, Salkia, Howrah, West Bengal 711106</li></ul></div><div><h4 className="mb-3 text-sm font-semibold">Hours</h4><ul className="space-y-2 text-sm text-muted-foreground"><li>Mon–Sun · 7am – 11pm</li></ul></div></div><div className="border-t border-border"><div className="mx-auto max-w-6xl px-6 py-4 text-xs text-muted-foreground"><div><a href="/admin" className="text-sm hover:underline transition">🔑 Admin Console</a></div>© 2026 Om Shree Krishna Caterer · All rights reserved.</div><div className="mx-auto max-w-6xl px-6 pb-4 text-center text-xs text-muted-foreground">Developer: Aniruddha Das | Developed by LeadSpree Business Solutions</div></div></footer>); }
function RootComponent() { const { queryClient } = Route.useRouteContext(); return <QueryClientProvider client={queryClient}><BrandProvider><OnboardingModal /><BrandResetButton /><div className="flex min-h-screen flex-col"><SiteHeader /><main className="flex-1"><Outlet /></main><SiteFooter /></div></BrandProvider></QueryClientProvider>; }
